# Generated by Django 4.1.2 on 2022-10-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowerShopApp', '0002_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='FlowerShopApp.product'),
        ),
    ]
