# Generated by Django 4.0.2 on 2022-11-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowerShopApp', '0003_alter_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='FlowerShopApp.Product'),
        ),
    ]
